### ISSUE TITLE
Conjunction-like multiword connectives in English: rather than, instead of, etc.

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/docs#679]
In EWT:

- _rather than_: `fixed(rather, than)`; sometimes attaches as `cc`, other times as `mark` or `case`
- _instead of_: `fixed(instead of)`; attaches as `mark` or `case` (except for 2 `advmod` attachments which do not use `fixed` and appear to be errors)
- _as well as_: `fixed(as, well)`, `fixed(as, as)`, attaches as `cc`
- _in addition to_: compositional analysis (`case(addition, in)`, etc.)
- _along with_: double `case` or double `mark`, except for 1 example using `fixed(along, with)` attaching as `cc`

_CGEL_ says that these expressions can be said to have been reanalyzed as compound coordinators (where they are between two contrasted items: _X rather than Y_, _X along with Y_, etc.).

Should we treat all of these as `fixed`, and as `cc` if connecting the two items? If appearing at the beginning of the clause, these expressions act like prepositions or subordinators, so `case`/`mark` would apply there:

- I ate an apple instead of a banana: `fixed(instead, of)`, `cc(banana, instead)`, `conj(apple, banana)`
- I ate an apple instead of eating a banana: `fixed(instead, of)`, `cc(eating, instead)`, `conj(ate, eating)`
- Instead of a banana, I ate an apple: `fixed(instead, of)`, `case(banana, instead)`, `nmod(apple, banana)`
- Instead of eating a banana, I ate an apple: `fixed(instead, of)`, `mark(eating, instead)`, `advmod(ate, eating)`

**Comment by dan-zeman** [comment]
To me it seems odd to say that the same two phrases, with the same conjunction word/expression, are in coordination when ordered A-B, and in subordination when ordered B-A. I would use `mark` or `case` in both situations.

As for _along with_, is it different from _with_? Because you can say _John with Mary did something_ and it is subordination, while in _John and Mary did something_ it is coordination.

**Comment by nschneid** [comment]
One argument in favor of the coordination analysis is that at least some of these items can conjoin a wide variety of constituent types:

- I ate _on the plane_ instead of _in the airport_.
- The shower had _tepid_ instead of _hot_ water.
- This time I was _fully_ instead of _partially_ awake.

It would be weird for an ADJ attaching as `amod` or an ADV attaching as `advmod` to have a `case` modifier, right?

> As for _along with_, is it different from _with_? Because you can say _John with Mary did something_ and it is subordination, while in _John and Mary did something_ it is coordination.

_John with Mary_ as the subject is odd; instead I'd say _John did something (along) with Mary_. There I'd definitely say it's `case`.

It is perhaps more conjunction-like in

- I bought _a hat_ along with _a cape_: If "along" is omitted it seems like the cape is an accessory to the hat, whereas "along with" essentially means "and also"

However, _along with_ may be the least grammaticalized as a coordinator. For me, _as well as_ meaning 'and' is more acceptable in cases like:

- I ate _on the plane_ as well as/??along with _in the airport_
- The room had _hot_ as well as/?along with _cold_ running water
- This time I was _physically_ as well as/?along with _mentally_ prepared

**Comment by Stormur** [comment]
Just my two cents.

Probably compounds like _instead of_ and _rather than_ are on their way of transition from prepositions towards "full" conjunctions (that is, in this case, admitting finite verbs), if it is true that the [majority of the speakers allow](https://www.thefreedictionary.com/instead+of), even if only at an informal level, a sentence like

- _We would have liked to buy instead of rent, but prices were just too high_

where, if I am not mistaken, speaking "formally" _renting_, i.e. a nominal (verb form), should appear.

Then, probably they should be treated everywhere as conjunctions, however I would not be so sure about their co-ordinating or subordinating status: your examples apparently show co-ordination, but can _instead of renting_ not be considered a (non-finite) subordinate clause? Is it possible that these compunds oscillate between `CCONJ` and `SCONJ`? This would indeed imply an oscillation between `cc` and `mark` in the current UD framework, but as Dan suggests, it would be very odd; it would be as if we assumed the existence of two different _instead of_'s. However, with _instead of_, can we exchange the two members and obtain the same meaning? Are 

- I ate apples instead of bananas.
- I ate bananas instead of apples

the same? It does not seem the case, whereas with co-ordinating conjunctions this happens:

- I didn't eat apples nor bananas. / I didn't eat bananas nor apples.
- I prefer bananas yet I ate apples. / I ate apples yet I prefer bananas.

(_yet_ seems to accept clauses only, probably because it is a conjunction derived from an adverb.)

In the end, probably the most consistent way to accommodate non-finite verbal constructions and constituents like those in _I ate on the plane instead of in the airport_, which seem to suggest that _instead of_ no longer behaves  (only) as a preposition, is, in spite of the _CGEL_, to always treat it as a comparative `SCONJ`, i.e. with deprel `mark`, and to assume a systematical ellipsis, as with many other comparative constructions, e.g.

- _Instead of [eating] bananas, I ate apples_ : `advcl(ate,bananas)`, `mark(bananas,instead)` 
- _I ate on the plane instead of [eating] in the airport_ : `advcl(ate,airport)`, `mark(airport,instead)`

The ellipsis explains why the inversion of the first element is possible as in _Instead of a banana, I ate an apple_, contrary to *_and bananas, I ate apples_.

I would not opt for the deprel `case` because I think that the following sentences

1. I ate instead of apples.
2. What did you ate? Apples instead of pears.

can not be considered (fully) grammatical, but correct me if I am mistaken. 1) would show that we do not have an argument of the verb, and 2) seems to suggest some anaphoric relation, so that the dependence of one element from the other seems to be questionable without assuming some sort of ellipsis and subordination.

Putting together al lthese tests, I would tentatively suggest:

- _rather than_, _instead of_, _as well as_: (comparative) `SCONJ` <-> `mark` (I formerly put _as well as_ as a `CCONJ`, but it is comparative)
- _in addition to_, _along with_: `ADP` <-> `case` (and of course `fixed`)

In the sentence _I bought a hat along with a cape_, I think that the issue is what to attach _a cape_ to (i.e. to _hat_ or to _bought_), but it is still is a (compound) preposition like the simple _with_ (a word which, by the way, interlinguistically and diachronically speaking, might well at some point overlap or pass into the realm of conjunctions).

**Comment by nschneid** [comment]
> -  We would have liked to buy instead of rent, but prices were just too high

Sounds perfectly natural to me.

"Q: What did you eat? A: Apples instead of pears." is also fine. (Assuming there are pragmatic reasons to mention that pears were not eaten.)

I would really prefer to avoid an ellipsis analysis unless absolutely necessary. Because of the nature of grammaticalization, I don't think we can get away with assuming that every word/fixed expression has the same function and POS in all its uses.

**Comment by nschneid** [comment]
...and in fact, it is not unusual for words to alternate as SCONJ vs. CCONJ in English (this was the motivation for the PTB tag `IN` lumping them together). I think what @dan-zeman was objecting to was using phrase order as the sole criterion for which one it is. But I think there are examples of "instead of" that look like CCONJ, others that look like SCONJ, and ones in between that we have to make a decision about.

**Comment by amir-zeldes** [comment]
Another difference is that 'instead', is an adverb, and can be used by itself:

I bought a book instead of a film.
I bought a book instead.

Compare:

I bought a book and a film
x I bought a book and

Etymologically, 'stead' is a noun, and "instead" is a PP, so it's natural that it has an adverbial distribution (cf. "she went in my stead"). The 'of' phrase is just the grammaticalized argument of "stead". I realize that etymological arguments are not necessarily a deciding factor, but in practice I find analyzing "instead of" as a coordination a little too avant garde and surprising for potential annotators and users, so I would vote for keeping it separate from the conj analysis.

**Comment by nschneid** [comment]
@amir-zeldes So do you favor ellipsis for "[fully instead of partially] awake"?

**Comment by Stormur** [comment]
> ...and in fact, it is not unusual for words to alternate as SCONJ vs. CCONJ in English (this was the motivation for the PTB tag `IN` lumping them together). I think what @dan-zeman was objecting to was using phrase order as the sole criterion for which one it is. But I think there are examples of "instead of" that look like CCONJ, others that look like SCONJ, and ones in between that we have to make a decision about.

What are examples of this CCONJ/SCONJ alternation? It still seems very strange to me. I can think of some co-ordinative constructions, e.g. with _and_, where there is some hint of sequentiality and so of subordination, but I think that their syntax stays co-ordinative.

Just two add another thought, I wonder if this difficulty of analysis, which in my experience is actually invasive for (among others) comparative constructions, would not warrant the introduction of a new kind of dependency relation, in particular that of correlation. This comes _inter alia_ from the observation that such comparative conjunctions seem to accept the "systematic ellipsis" I mentioned, while other `SCONJ` do not, and it is this correlation that at some point appears to us as a co-ordination, but it is rather a **subordinative correlation**.

**Comment by nschneid** [comment]
Apparently I'm losing my mind: I meant ADP/SCONJ alternation, not CCONJ/SCONJ. There's no need to say "instead of" is always SCONJ and never ADP because plenty of prepositions ("in", "with", "before", "after", etc.) can double as SCONJ:

- Instead of having an apple, I'll have a pear. - SCONJ
  * After having an apple, I'll have a pear. - SCONJ
- Instead of an apple, I'll have a pear. - ADP
  * After an apple, I'll have a pear. - ADP

(As a matter of fact, *CGEL* lumps ADPs and most SCONJs together, mirroring the PTB `IN` category. But that is a departure from the traditional terminology, and one of UD's principles is to try to use traditional terminology where possible.)

**Comment by Stormur** [comment]
Of course I am very aware of this fact and of the ADP/SCONJ alternation, which is sometimes difficult to tackle during annotation.

In my intervention before, however, this possible alternation puzzled me, because I am not sure it is the case:

> I would not opt for the deprel case because I think that the following sentences
> 
>    1.  I ate instead of apples.
>    2. What did you ate? Apples instead of pears.
>
> Sentence 1) would show that we do not have an argument of the verb

When we have a "true" preposition, sentence 1. becomes acceptable, at least syntactically if not quite semantically:

- 1a) I ate after the apples.
- 1aa) After an apple, I ate.

As @amir-zeldes pointed out, the etymological argument can help us by noticing that _instead of_ is of adverbial origin, and that the _of_ just serves to add an argument to the adverb _instead_. So, probably the compound _instead of_ has actually never functioned as an adposition (contrary to what I stated before).

So, I would argue that _instead of_ cannot be annotated with `case`, because it never introduces an argument of a verb or a noun and it does not function as a preposition. The fact that 2) is still acceptable (given some previous information) and 1) is not derives in my opinion from the fact that _instead of_ requires a correlation. Now, a correlating element belongs more to the field of conjugations, at least in the UD framework, and, among others since there is no symmetry, to subordinating conjunctions. Then, we might discuss if correlation really differs from co-ordination and subordination, being somewhere in-between.

Then, with regard to _after_, I think that it actually always functions as an ADP, and it should probably be having to variate between NOUN and VERB, rather than after between ADP and SCONJ. But here we come again to the very difficult position of nominal verb forms in the UD framework...

**Comment by amir-zeldes** [comment]
RE the ellipsis question, I don't think ellipsis is needed:

[fully instead of partially] awake
nmod(fully,partially)
case(partially,instead)
fixed(instead,of)

Compare:
[fully as an alternative to partially] awake
nmod(fully,alternative)
case(alternative,as)
nmod(alternative,partially)

The fact that "partially" refers semantically to being awake is the same in both cases, but I think it's uncontroversial that the second case should be `nmod(alternative,partially)`. If we accept that example, then I think it's fair to see [fully instead of partially] as a complex modifier, and leave the semantic dependencies to a separate level of analysis (at least as long as we're sticking to proper trees).

**Comment by amir-zeldes** [comment]
@Stormur I agree that "instead of" has an adverbial function, but I'm not saying it can't be analyzed as a preposition synchronically. PPs are basically adverbials with a nominal argument, and the entire "instead of" (using `fixed`) has the distribution of a preposition, which can take nominals or clauses (in which case it becomes `mark` instead of `case` in UD, but that's normal). 

BTW if the etymology is interesting with respect to the grammaticalization, comparison might be too: in German, the equivalent 'statt' can be used with out a preposition like "in", and with a bare object without "of", but in the genitive:

  * A anstatt B (complex preposition, an+statt ~ on+stead)
  * A statt B (simple preposition, ~ "A stead B")
  * an seiner statt (archaic nominal version, corresponds to English "in his stead")

All of which is to say, a cousin of English would also like this thing to be a preposition, and has almost gotten rid of the historical disruptions to this process.

**Comment by nschneid** [comment]
@amir-zeldes Instead of (ha) `nmod(fully,alternative)`, shouldn't it be `obl`? [`nmod`](https://universaldependencies.org/u/dep/nmod.html) refers to "nominal dependents of another noun or noun phrase". [`obl`](https://universaldependencies.org/u/dep/obl.html) says "a nominal...[that] functionally corresponds attaching to a verb, adjective or other adverb".

But that's because "alternative" is a noun. I don't see how `nmod(fully,partially)` or `obl(fully,partially)` could be right because both words are adverbs. If anything I would think it would be `advmod(fully,partially)` and `case(partially, instead)`. But an `advmod` dependent having a case marker seems counterintuitive.

**Comment by nschneid** [comment]
> I would argue that _instead of_ cannot be annotated with `case`, because it never introduces an argument of a verb or a noun

Not sure I follow the argumentation here. Consider:

- After dinner, I napped. / I napped after dinner.
- Instead of dinner, I napped. / I napped instead of dinner.

These look like adverbial PPs to me, hence `obl` + `case`.

**Comment by amir-zeldes** [comment]
@nschneid yes, sorry, should be `obl`!

But I stand by obl+case rather than advmod: I think in general, when we have an adverb modified via a case we treat it like conversion, e.g.

They will sell to them cheaply on top of exclusively
nmod(top,exclusively)
case(exclusively,of)

It think this is better than having advmod+case, since the 'advmodyness' of "exclusively" is now mainly in its indirect semantic relationship with 'sell', but syntactically, "exclusively" is subordinate to "top".

**Comment by Stormur** [comment]
> > I would argue that _instead of_ cannot be annotated with `case`, because it never introduces an argument of a verb or a noun
> 
> Not sure I follow the argumentation here. Consider:
> 
>     * After dinner, I napped. / I napped after dinner.
> 
>     * Instead of dinner, I napped. / I napped instead of dinner.
> 
> 
> These look like adverbial PPs to me, hence `obl` + `case`.

Sorry, I explained my argument somewhat tersely there. 

Your second sentence looks problematic to me... is it really accepted by the majority of the speakers? I wonder if _dinner_ can be used as a verb (in Italian e.g. we have the direct derivation _cenare_ from _cena_), but isn't something missing? It could be _have dinner_, or _prepare_, or _watching my friend preparing dinner_, why not? We just interpolate it with the most probable expression "have dinner", and this might be prompted by the fact that _have_ is a light verb here, so _dinner_ can be accepted to stand alone because it actually bears the semantic weight and _have_ is the "least difficult" choice (and a signal is that it has no article, see my example below). But I still see it as an ellipsis: 

* Instead of [having] dinner, I napped.

So you have a correlation between two actions (here, verbs). These expressions like _instead of_, _rather than_, _as well as_, are all binary, they require two elements. Would you accept:

* Instead of the book, I went out for a walk.

Do we assume _buy_, _read_, _throwing away_, _give as a present_...? I don't know if it is acceptable, because it seems to me that this indeterminateness comes from a kind of anacoluthon. There is no syntactic coherence. 

So I would have the analysis:

* `root(napped) nsubj(napped,I) advcl(napped,dinner) mark(dinner,instead) fixed(instead,of)`

**Comment by amir-zeldes** [comment]
Yesterday Nathan and I figured out offline that there's another argument for case over cc: "instead of" assigns oblique case to object pronouns, and is incompatible with what's left of the English nominative. Compare:

instead of me
x instead of I

As opposed to:
and/or/but me
and/or/but I

This is due to the historical source again: instead of has the distribution of a preposition because it begins with what used to be a preposition (in) and governs like a preposition because it ends with one (of). 

The interchangeable semantics of the two linked items comes from the facts that 'instead' signals an alternative, so naturally it can appear with many categories as long as they are contextually alternatives to each other. But syntactically, I think the whole thing behaves like a preposition (if we accept the `fixed` part).

**Comment by nschneid** [comment]
I did a COCA search and there are a couple legitimate tokens of "instead of I", but I think most people would say "instead of me". So that is indeed a respect in which it is preposition-like.

I can think of a couple other respects in which it potentially is conjunction-like, though these are probably rare:

* Non-constituent coordination: 
  - Would you prefer to cook [Mary lunch] or/instead of [Adam dinner]? – "instead of" sounds OK to me, though other speakers may disagree
* Adjectives modifying both conjuncts:
  - Do you want new PENCILS instead of MARKERS? - with appropriate intonational stress I would read this as 'instead of new markers'.

That said, I realize it would be difficult for annotators to draw a line between CCONJ and ADP/SCONJ, so I am OK with just using `fixed(instead, of)` and treating it as `case` or `mark`.

**Comment by nschneid** [comment]
@Stormur, to your point, I would agree that *semantically* "instead of" requires two similar things (e.g. two entities or events) to compare. But syntactically, I at least feel the flexibility to say something like "Instead of the book, I went out for a walk." given the right context (if it was established that I had planned to read a book and then changed my mind). Other native speakers may disagree; I'm not sure. But saying that it can alternate between `case` and `mark` is consistent with many other grammatical connectives in English and would probably be simpler for annotators than the ellipsis analysis.

**Comment by amir-zeldes** [comment]
The mark/case alternation just depends on the object type, and with gerunds tagged VERB, we have to use `mark` by the guidelines:

instead/SCONJ+mark of seeing/VERB+advcl it 

BTW it's not just "instead of", I think other complex expressions specifying alternatives could behave this way semantically, and I wouldn't want them to be `cc` just due to that context. The English guidelines treat "as opposed to" with a nominal as case+fixed:

as opposed to Mary 
case(Mary,as)
fixed(as,opposed)
fixed(as,to)
https://universaldependencies.org/en/dep/fixed.html

If we accept this analysis, then the following unlike coordination should still be advcl+mark, even though the contrast is with a nominal (party):

I wanted a party as opposed to feeling like this is a funeral
mark(feeling,as)
fixed(as,opposed)
fixed(as,to)

And this shares the property of sounding bad with I, due to its oblique origins:

x as opposed to I

**Comment by Stormur** [comment]
So, I reasoned some more about this issue and I hope in the following to address all your points in a clearer way than before without being too repetitive. Beware, it is quite a lenghty post...

The fact that pronouns after _instead of_ normally have an oblique form comes, as you said, from the fact that we historically have the argument of an adverb. Still, @nschneid noted some "legitimated couples of _instead of I_", so there actually seems to be this possibility (by the way, how do we interpret _Instead of I'm going to be [...]_, found in COCA?). In fact, the use of oblique pronoun forms is by itself not a definitive argument, if we observe cases like _It was me_, where formally _I_ should appear. In any case, we can see the morphological case just as a historical remnant that can be trumped by other syntactical relations.

However, I am not really sure that the distribution of such a compound is the same as a preposition. We just have a prepositional element as a "junction", but then we admit constructions like "instead of in the airport". Is something like _I am not sure with in the airport_ acceptable? It is true that many English prepositions come from such "stackings", like _within_ or _into_, but then they form a whole unit, whereas _instead of in_ does not. 

Now, to assess the role of _instead of_ & co, I tried to start anew from the simple adverb:

- I ate apples instead.

We have: `root(ate) obj(ate,apples) nsubj(ate,I) advmod(ate,instead)`
If we took _in+stead_ we would have an `obl+case`, which is actually the nominal equivalent of `advmod`.

- [ ]  To bring forth an interesting interlinguistic comparison, I note that the Duden grammar of German  identifies a class of _Konjunktionaladverbien_, almost seen as as a "transitional state" from adverb to conjunctions. The Duden is explicit about it, but many other grammars have ambivalent stances for similar words (e.g. some Italian grammars choose to treat them as conjunctions but mention the classification problem; one of the most prominent [Greek dictionaries](http://www.greek-language.gr/greekLang/modern_greek/tools/lexica/triantafyllides/search.html?lq=%CE%B1%CE%BD%CF%84%CE%AF&dq=) classifies αντί 'instead' as a preposition, but then notes its conjunctival use and mentions systematic ellipsis).

Now, we add an argument to the adverb by means of a conjoining particle, a preposition:

- I ate apples instead of pears.

We have: `root(ate) obj(ate,apples) nsubj(ate,I) advmod(ate,instead) obl(instead,pears) case(pears,of)`
If we were to use enhanced dependences, we might add a relation `corr(pears,apples)` to show that both elements are intended to represent the same syntactic role (here, object).

Next, we can consider a grammaticalisation of _instead of_, so we would have: `root(ate) obj(ate,apples) nsubj(ate,I) obl(ate,pears) case(pears,instead+of)` (_instead+of_ shortens the `fixed` relation)

So, yes, we might consider _instead of_ an element introducing an oblique argument (= noun equivalent of `advmod`), **but** one which depends on the main predicate. Now, we might be tempted to shift the relation `obl(ate,pears)` to having head _apples_, directly showing the correlation:

`root(ate) obj(ate,apples) nsubj(ate,I) **?dep(apples,pears)** ?case(pears,instead+of)`

So this `?dep` is a kind of shortcut of `obl(ate,pears)` + `corr(pears,apples)`. But what should it be?

Let's keep `case`. For nouns, we have the choice between `nmod`, `appos` and `nummod`. I think we can discard the latter two. Then, the problem with `nmod` here is that we do not really have a "[functionally [...] attribute or genitive complement](https://universaldependencies.org/u/dep/nmod.html)". It is a completely different relation than in e.g.

- I took [the book for the store].

There, _store_ is not meant to fulfil the role of object like _book_. 

Neither can we use `obl`. The only relation that we might use, and that can accommodate all kinds of pairs _X instead of Y_, should imply some co-ordination like `conj`, implying `cc` for _instead+of_. But then we get problems like the fact that we can accept _Instead of pears, I ate apples_, whereas this is not possible with usual co-ordinators, and, on a semantic level, the inversion _I ate pears instead of apples_ has the exactly opposite meaning (while something like _I took [the store for the book]_ has a completely unrelated meaning to its original sentence), so there actually is some kind of subordination (besides, the "dislocation" is acceptable for subordinate clauses). 

So, what to do? I think that we have two main choices:
1. We want to have a direct dependency relation in the main syntactic tree between the two objects linked by _instead of_;
2. We transfer this relation to the enhanced tree and keep the "original" structure.

In 1), either we use new relations, e.g. `scorr` ("subordinative correlation") and `scr` ("subordinative correlator"), or we use existing ones in a not so appropriate way, e.g. `conj:scorr` and `cc:scorr` (the structure of the tree is the same). We might have an alternation `scorr`/`obl` - `scr`/`case`. Let's consider:

a) Instead of dinner, I napped.
b) I ate apples instead of pears.
c) I slept at home instead of in the airport.
d) She is partially instead of fully awake.
e) I read instead of dancing.

Choice 1):

- 1a) `root(napped) nsubj(napped,I) obl(napped,dinner) case(dinner,instead+of)` (no clear correlation)
- 1b) `root(ate) obj(ate,apples) nsubj(ate,I) scorr(apples,pears) scr(pears,instead+of)`
- 1c) `root(slept) nsubj(slept,I) obl(slept,home) case(home,at) scorr(home,airport) case(airport,in) det(airport,the) scr(airport,instead+of)` 
- 1d) `root(awake) cop(awake,is) nsubj(awake,she) advmod(awake,partially) scorr(partially,fully) scr(fully,instead+of)`
- 1e) `root(read) nsubj(read,I) advcl(read,dancing) mark(instead+of)` 

Choice 2): it might be necessary to assume ellipses (verbal or nominal).

- 2a) `root(napped) nsubj(napped,I) obl(napped,dinner) case(dinner,instead+of)` (no enhanced dependencies)
_or_ 
2a')  `root(napped) nsubj(napped,I) advcl(napped,dinner) mark(dinner,instead+of)` (dubious ellipsis; no enhanced dependencies)
- 2b)  `root(ate) obj(ate,apples) nsubj(ate,I) obl(ate,pears) case(pears,instead+of)`; enh.dep.`corr(pears,apples)`
_or_
2b')  `root(ate) obj(ate,apples) nsubj(ate,I) advcl(ate,pears) mark(pears,instead+of)`; enh.dep.`corr(pears,apples)`
- 2c)  `root(slept) nsubj(slept,I) obl(slept,home) case(home,at) advcl(slept,airport) case(airport,in) det(airport,the) mark(airport,instead+of)` (ellipsis preferred because of conflicting `case`s); enh.dep. `corr(airport,home)` 
- 2d) `root(awake) cop(awake,is) nsubj(awake,she) advmod(awake,partially) advcl(awake,fully) mark(fully,instead+of)` (ellipsis preferred to `advmod(awake,fully)` to avoid `obl(awake,fully)` and incongruent `case(fully,instead+of)`); enh.dep. `corr(fully,partially)` 
- 2e) `root(read) nsubj(read,I) advcl(read,dancing) mark(instead+of)`; enh.dep. `corr(dancing,read)` (this `advcl` might already be seen to incorporate a  `corr`)


1a) and 2a) are the same in both models. This might correspond to a new use of the compound that foregoes a correlation and becomes closer to a more prototypical preposition like _after_ (in fact, adversative, comparative and temporal phrases can overlap). But I see this as a **further evolution** of _instead of_ rather than its original state! Besides this case, in both models the annotation is homogenous for all cases. For strategy 2) the assumption of an ellipsis seems to be the more general and "cleaner" solution, without having to alternate between `mark` and `case`.

Sorry for the very long posts... one of the reasons I was so thourough is that similar constructions, especially comparative ones with _quam_, have become a heartfelt problem in the annotaiton of Latin and we are trying to find the right strategy.

* * *

PS:

> I wanted a party as opposed to feeling like this is a funeral

Isn't the contrast here between "to want a party" and "to feel like this is a funeral"? To have an opposition of nouns, shouldn't we put _the_ before _feeling_?

**Comment by nschneid** [comment]
> However, I am not really sure that the distribution of such a compound is the same as a preposition. We just have a prepositional element as a "junction", but then we admit constructions like "instead of in the airport". Is something like _I am not sure with in the airport_ acceptable? It is true that many English prepositions come from such "stackings", like _within_ or _into_, but then they form a whole unit, whereas _instead of in_ does not.

The fact that "instead of" can connect two adverbials (e.g. "I am here instead of in the airport") is consistent with my point that it bears some similarities with coordinating conjunctions. However, there *are* prepositions that stack with other prepositions: "He emerged __from under__ the table". So I don't see a slam-dunk argument that we have to allow instead+of to be a coordinator.

> the problem with `nmod` here is that we do not really have a "[functionally [...] attribute or genitive complement](https://universaldependencies.org/u/dep/nmod.html)".

I don't know how strict that requirement about attributes/genitives is. My understanding is that (at least for English), whenever we want to analyze a noun as having a PP modifier, we call the relation `nmod`.

So if we have the bracketing "I ate [apples instead+of pears]", either `nmod(apples, pears)` or `conj(apples, pears)` seems plausible to me. There is also the possible bracketing "I ate apples [instead+of pears]", i.e. `obl(ate, pears)`.

For "Instead of pears, I ate apples" it would have to be `obl(ate, pears)`.

> new relations, e.g. `scorr` ("subordinative correlation") and `scr` ("subordinative correlator")

These seem to me like semantic relations rather than syntactic (even enhanced-syntactic) relations. Consider: 

- Instead of salt, I wish that John would consider adding some pepper.
- Instead of Mary, I wish that John would consider adding some pepper.

Part of interpretation requires the listener to realize that "salt" and "pepper" are likely to be contrasted in the first case, and "Mary" and "John" in the second case. There's nothing syntactic that requires one or the other (the relation is anaphoric).

> > I wanted a party as opposed to feeling like this is a funeral
> 
> Isn't the contrast here between "to want a party" and "to feel like this is a funeral"? To have an opposition of nouns, shouldn't we put _the_ before _feeling_?

It sounds grammatical to me.

**Comment by amir-zeldes** [comment]
I agree with @nschneid : I think relations like scorr/scr are interesting, but I think they are part of semantics, not syntax. The same could be said about any adverbial suggesting a relationship, such as:

I would be willing to consider apples as an alternative to pears

Despite the indirect semantic relationship between pears and apples in this example, the syntax for me would be:

obl(consider,alternative)
nmod(alternative,pears)

With no syntactic edges of any kind between apples and pears.

**Comment by arademaker** [comment]
> Of course I am very aware of this fact and of the ADP/SCONJ alternation, which is sometimes difficult to tackle during annotation.

Hi @Stormur and others. This is still not 100% clear to me. In principle, ADP introduces a nominal and SCONJ a clause. But ADP doc says:

> Adpositions belong to a closed set of items that occur before (preposition) or after (postposition) a complement composed of a noun phrase, noun, pronoun, or **clause that functions as a noun phrase**...

but what clause that functions as NP, being a clause headed by a VERB, would be introduced by an ADP instead of SCONJ?

**Comment by amir-zeldes** [comment]
@arademaker For English that sounds right - it would be SCONJ based on the current practices.

I'm not sure what the intention of the universal documentation was, but some languages can 'package' clauses into something that then functions 100% like a noun. For example Japanese nominalizers like -no or -koto can basically be suffixed to a clause, and then you can use them as any kind of argument or adjunct, stick postpositions on them, etc. Maybe European languages are not so different in principle, but it's very transparent and regular in languages like Japanese.

**Comment by Stormur** [comment]
> > Of course I am very aware of this fact and of the ADP/SCONJ alternation, which is sometimes difficult to tackle during annotation.
> 
> Hi @Stormur and others. This is still not 100% clear to me. In principle, ADP introduces a nominal and SCONJ a clause.
 
Hi! 

I was referring to the fact that a very widespread phenomenon is for the same element to function in different contexts as a preposition (introducing noun phrases), a conjunction (introducing clauses) or also as an adverb. 

>But ADP doc says:
> 
> > Adpositions belong to a closed set of items that occur before (preposition) or after (postposition) a complement composed of a noun phrase, noun, pronoun, or **clause that functions as a noun phrase**...
> 
> but what clause that functions as NP, being a clause headed by a VERB, would be introduced by an ADP instead of SCONJ?

The key point here is to distinguish two levels: on the one hand parts of speech, with `ADP` and `SCONJ`, and on the other hand syntactic relations `case` (for nominals) and `mark` (for verb/predicates). 

You can have an adposition bound to the nominal form of a verb: it is still an adposition, because it is still functioning in a nominal context and possibly it is never used to link (finite) clauses, so it stays `ADP`, but the fact that it is modifying a `VERB` is signalled by `mark`. By contrast, an `SCONJ` would not be able to appear in the same context. So this happens when a clause is inserted into a sentence "disguised" as a noun phrase. But it never happens for an `SCONJ`.

**Comment by dan-zeman** [comment]
A potential example of a `SCONJ` for which this happens is _than_ (and its equivalents in other languages) in [Comparative Constructions](https://universaldependencies.org/workgroups/newdoc/comparatives.html#periphrastic-gradation).

**Comment by Stormur** [comment]
Oh, right! I have to admit that in those cases I am preferring the reading as an elliptical comparative clause, so I forgot.

Are there other cases apart from comparatives?
